function dx = x_dot(x,u,th,var)
    if var == 0
    % исходная (проверено)
        coeff = 1/(th(1)*th(2)-((th(3))^2)*((cos(x(3)))^2));
        dx(1) = x(2);
        dx(2) = coeff*(th(2)*u + th(2)*th(3)*sin(x(3))*(x(2))^2 + ...
                     2*th(2)*th(3)*sin(x(3))*x(2)*x(4) + th(2)*th(3)*sin(x(3))*(x(4))^2 + ...
                     ((th(3))^2)*sin(x(3))*cos(x(3))*(x(2))^2 - th(6)*th(2)*th(4)*cos(x(1)) + ...
                     th(6)*th(3)*th(5)*cos(x(3))*cos(x(1) + x(3)));
        dx(3) = x(4);
        dx(4) = coeff*(- th(2)*u - th(3)*cos(x(3))*u - ...
                     th(1)*th(3)*sin(x(3))*(x(2))^2 - th(2)*th(3)*sin(x(3))*(x(2))^2 - ...
                     th(2)*th(3)*sin(x(3))*(x(4))^2 - 2*th(2)*th(3)*sin(x(3))*x(2)*x(4) - ... 
                     (th(3))^2*sin(x(3))*cos(x(3))*(2*(x(2))^2 + 2*x(2)*x(4) + (x(4))^2) - ...
                     th(6)*th(1)*th(5)*cos(x(1)+x(3)) + th(6)*th(2)*th(4)*cos(x(1)) - ...
                     th(6)*th(3)*cos(x(3))*(th(5)*cos(x(1)+x(3)) - th(4)*cos(x(1))));   
    elseif var == 1
    % упрощенная (как в статье, но без ошибок)
        coeff = 1/(th(1)*th(2)-((th(3))^2));
        dx(1) = x(2);
        dx(2) = coeff*(th(2)*u - ...
                     th(6)*th(2)*th(4)*cos(x(1)) + ...
                     th(6)*th(3)*th(5)*cos(x(3))*cos(x(1) + x(3)));
        dx(3) = x(4);
        dx(4) = coeff*(- th(2)*u - th(3)*cos(x(3))*u - ...
                     th(6)*th(1)*th(5)*cos(x(1)+x(3)) + th(6)*th(2)*th(4)*cos(x(1)) - ...
                     th(6)*th(3)*cos(x(3))*(th(5)*cos(x(1)+x(3)) - th(4)*cos(x(1)))); 
    elseif var == 2
    % уравнения, не исключающие трение
        g = th(6); b1 = th(7); b2 = th(8);
        coeff = 1/(th(1)*th(2)-((th(3))^2)*((cos(x(3)))^2));
        dx(1) = x(2);
        dx(2) = coeff*(th(2)*u + th(2)*th(3)*sin(x(3))*(x(2))^2 + ...
                     2*th(2)*th(3)*sin(x(3))*x(2)*x(4) + th(2)*th(3)*sin(x(3))*(x(4))^2 + ...
                     ((th(3))^2)*sin(x(3))*cos(x(3))*(x(2))^2 - g*th(2)*th(4)*cos(x(1)) + ...
                     g*th(3)*th(5)*cos(x(3))*cos(x(1) + x(3)) - ...
                     th(2)*b1*x(2) + (th(2) + th(3)*cos(x(3)))*b2*x(4));
        dx(3) = x(4);
        dx(4) = coeff*(- th(2)*u - th(3)*cos(x(3))*u - ...
                     th(1)*th(3)*sin(x(3))*(x(2))^2 - th(2)*th(3)*sin(x(3))*(x(2))^2 - ...
                     th(2)*th(3)*sin(x(3))*(x(4))^2 - 2*th(2)*th(3)*sin(x(3))*x(2)*x(4) - ... 
                     (th(3))^2*sin(x(3))*cos(x(3))*(2*(x(2))^2 + 2*x(2)*x(4) + (x(4))^2) - ...
                     g*th(1)*th(5)*cos(x(1)+x(3)) + g*th(2)*th(4)*cos(x(1)) - ...
                     g*th(3)*cos(x(3))*(th(5)*cos(x(1)+x(3)) - th(4)*cos(x(1))) + ...
                     (th(2) + th(3)*cos(x(3)))*b1*x(2) - ...
                     (th(1) + th(2) + 2*th(3)*cos(x(3)))*b2*x(4)); 
    end
    dx = dx'; % недавно добавил
end