function dx = x_dot_lower_eq(x, u, theta)
    coeff = 1/(theta(1)*theta(2)-((theta(3))^2)*((cos(x(3)))^2));
    dx_1 = x(2);
    dx_2 = coeff*(theta(2)*u + theta(2)*theta(3)*sin(x(3))*(x(2))^2 + ...
                 2*theta(2)*theta(3)*sin(x(3))*x(2)*x(4) + theta(2)*theta(3)*sin(x(3))*(x(4))^2 + ...
                 ((theta(3))^2)*sin(x(3))*cos(x(3))*(x(2))^2 - theta(6)*theta(2)*theta(4)*sin(x(1)) + ...
                 theta(6)*theta(3)*theta(5)*cos(x(3))*sin(x(1) + x(3)) - ...
                 theta(2)*theta(7)*x(2) + (theta(2) + theta(3)*cos(x(3)))*theta(8)*x(4));
    dx_3 = x(4);
    dx_4 = coeff*(- theta(2)*u - theta(3)*cos(x(3))*u - ...
                 theta(1)*theta(3)*sin(x(3))*(x(2))^2 - theta(2)*theta(3)*sin(x(3))*(x(2))^2 - ...
                 theta(2)*theta(3)*sin(x(3))*(x(4))^2 - 2*theta(2)*theta(3)*sin(x(3))*x(2)*x(4) - ... 
                 (theta(3))^2*sin(x(3))*cos(x(3))*(2*(x(2))^2 + 2*x(2)*x(4) + (x(4))^2) - ...
                 theta(6)*theta(1)*theta(5)*sin(x(1) + x(3)) + theta(6)*theta(2)*theta(4)*sin(x(1)) - ...
                 theta(6)*theta(3)*cos(x(3))*(theta(5)*sin(x(1) + x(3)) - theta(4)*sin(x(1))) + ...
                 (theta(2) + theta(3)*cos(x(3)))*theta(7)*x(2) - ...
                 (theta(1) + theta(2) + 2*theta(3)*cos(x(3)))*theta(8)*x(4)); 
    dx = [dx_1; dx_2; dx_3; dx_4];
end